export { default as Collection } from "./Collection/Collection";
export { default as Home } from "./Home/Home";
export { default as Support } from "./Support/Support";
export { default as ManageCollection } from "./ManageCollection/ManageCollection";
export { default as ManageUsers } from "./ManageUsers/ManageUsers";
export { default as MyTrees } from "./MyTrees/MyTrees";
export { default as BuyTrees } from "./BuyTrees/BuyTrees";
export { default as Story } from "./Story/Story";
export { default as AboutUs } from "./AboutUs/AboutUs";
